### ISSUE TITLE
First Titanium app link is not working

### ISSUE THREAD

**Issue by AvinashDalvi89** [tidev/titanium-docs#110]
In this page https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Getting_Started/#first-titanium-app when click on 
[Hello Titanium App Tutorial](https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Getting_Started/Hello_Titanium_App_Tutorial/). wrong link is there. it should be https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_Getting_Started/Hello_Titanium_App_Tutorial.html

**Comment by AvinashDalvi89** [comment]
I would take this.

**Comment by caspahouzer** [comment]
Thank you for this report. We’ll fix that

**Comment by AvinashDalvi89** [comment]
Also [Edit this page on GitHub](https://github.com/tidev/titanium-docs/edit/master/docs/guide/Titanium_SDK/Titanium_SDK_Getting_Started/README.md) this link also broken in same page

**Comment by AvinashDalvi89** [comment]
Can I contribute @caspahouzer  ?

**Comment by caspahouzer** [comment]
Every help is welcome

https://github.com/tidev/organization-docs/blob/main/AUTHORIZED_CONTRIBUTORS.md
