### ISSUE TITLE
Regen not working

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-docs#121]
I've made an update to the ti.crypto docs and the regen workflow is not working:
https://github.com/tidev/ti.crypto/actions/workflows/regen-docs.yml
`Error: Parameter token or opts.auth is required`

@cb1kenobi might want to check that

**Comment by cb1kenobi** [comment]
I don't get it. It should work. Will need to investigate.

**Comment by cb1kenobi** [comment]
I regenerated the token and did a bunch of testing. I believe it's resolved now.

I found that the code run in the Regen Docs action is that at the point of time of the pull request. So, just in case, I added a manual workflow trigger to the Regen Docs action and will update every repo. That way if a branch that is out-of-date is merged, we can still manually trigger the event (and test it) from whichever repo triggered the change.

**Comment by caspahouzer** [comment]
Thank you so much
