### ISSUE TITLE
Apple signin docs are broken

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-docs#159]
https://titaniumsdk.com/api/modules/applesignin produces a 404

The build log produces many `[vuepress] No matching page found for sidebar item "/api/modules/applesignin/loginbutton"`  errors:
https://github.com/tidev/titanium-docs/actions/runs/3350934263/jobs/5552059066#step:5:106

Docs are in: https://github.com/tidev/titanium-apple-sign-in/tree/master/apidoc

**Comment by ewanharris** [comment]
Think the configured [repo is just wrong](https://github.com/tidev/titanium-docs/blob/main/.github/workflows/regen.yml#L133-L138), will PR

**Comment by m1ga** [comment]
didn't work :( Still `No matching page found for sidebar item "/api/modules/applesignin/loginbutton" ` and the 404

**Comment by ewanharris** [comment]
I wonder if the apple-sign-in vs applesignin is the issue maybe? Although others don't seem to use the complete path, will have to look locally

**Comment by m1ga** [comment]
the files are there now https://titaniumsdk.com/api/modules/applesignin.html no sure when that happend :smile:
