### ISSUE TITLE
Search: Selecting a property / method / event does not scroll to the section

### ISSUE THREAD

**Issue by hansemannn** [tidev/titanium-docs#82]
When selecting a property / method / event of an API in the search (e.g. `addMarker` in `Ti.UI.ListView`), the search redirects to `Ti.UI.ListView` but does not scroll to the anchor (e.g. `#addmarker`) of the API. When reloading the page or manually pasung the link, it works. So it seems to be a routing issue.

**Comment by m1ga** [comment]
Fix: https://github.com/tidev/docs-devkit/pull/218
