### ISSUE TITLE
Left sidebar (Globals, Node.js, ...) click not working when clicking on title directly

### ISSUE THREAD

**Issue by hansemannn** [tidev/titanium-docs#83]
When selecting one of the left sidebar items via clicking on the title, the accordion does not expand. It does work when clicking right next to the title and also works when clicking on the arrow directly

<img width="312" alt="Bildschirmfoto 2022-01-28 um 11 35 28" src="https://user-images.githubusercontent.com/10667698/151532166-a7c02f16-caa3-4da1-936e-a3fcd5c1579c.png">
.

**Comment by m1ga** [comment]
Had to add some pages to the menu and had a look at this one too. If you want to review: https://github.com/tidev/titanium-docs/pull/193
